const fs=require('fs'),vm=require('vm'),assert=require('assert');
const app=fs.readFileSync('app.js','utf8'),ctx={state:{data:{}},esc:s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))};vm.createContext(ctx);
vm.runInContext(app.slice(app.indexOf('const rooms='),app.indexOf('function esc('))+fs.readFileSync('librarian.js','utf8')+`;globalThis.model={librarianLessons,foliantDrama,foliantDebates,foliantPicks,foliantAudioReasons,foliantAudioBrowse,foliantAudioClues};globalThis.sourceIDs=sources.map(s=>s[0]);globalThis.intro=librarianBookIntro;globalThis.recommend=foliantRecommendationSpeech;`,ctx);
const normalize=t=>t.normalize('NFKC').replace(/\s+/g,' ').trim().replace(/[.!]+$/,'');
const manifest=JSON.parse(fs.readFileSync('assets/foliant-audio/manifest.json')),lookup=new Map(manifest.map(r=>[normalize(r.text),r]));let checked=0;
function covered(phrases){for(const p of phrases){assert(lookup.has(normalize(p)),'Missing audio: '+p);checked++;}}
const decode=s=>s.replace(/<[^>]+>/g,'').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
for(const [id,lesson] of Object.entries(ctx.model.librarianLessons)){
 covered([lesson.hello,lesson.prompt,lesson.bridge]);
 for(const kind of ['experiment','resource','question'])for(const sid of ctx.sourceIDs){const html=ctx.intro(id,kind,sid);covered([...html.matchAll(/<(h3|li)\b[^>]*>(.*?)<\/\1>/gs)].map(m=>decode(m[2])));}
 const d=ctx.model.foliantDrama[id];covered([d.speech,d.task,d.question,...d.replies]);for(const v of d.voices)covered(v.slice(1));
}
for(const d of ctx.model.foliantDebates)covered([d.title,d.claim,d.a,d.b,...d.replies]);
for(const pick of [...ctx.model.foliantPicks,{title:'Ein unbekannter Band',author:'Eine Autorin'},...Object.keys(ctx.model.foliantAudioClues).map(title=>({title,author:'Eine Autorin'}))])for(const mood of [undefined,...Object.keys(ctx.model.foliantAudioReasons)])for(const answer of [undefined,'liked','different','shorter','unread'])covered(ctx.recommend(pick,{mood,last:answer?{answer}:null}));
for(const r of manifest)assert(fs.statSync(r.file).size>1000,'Invalid audio file '+r.file);
let audio,plays=[],robotCalls=0;const elements=new Map();const runtime={URL,location:{href:'https://example.org/'},window:{speechSynthesis:{}},speechSynthesis:{cancel(){},speak(){robotCalls++}},console,document:{getElementById:id=>{if(!elements.has(id))elements.set(id,{value:'1',parentElement:{}});return elements.get(id)},querySelectorAll:()=>[],addEventListener(){}},Audio:class{constructor(){audio=this}pause(){}play(){plays.push(this.src);return Promise.resolve()}},fetch:async()=>({ok:true,json:async()=>manifest})};vm.createContext(runtime);vm.runInContext(fs.readFileSync('reader.js','utf8')+';globalThis.test=BabelAudio;',runtime);
(async()=>{const phrases=[ctx.model.librarianLessons.attention.hello,ctx.model.foliantDrama.attention.replies[0]];await runtime.test.speak(phrases);assert(plays[0].endsWith(lookup.get(normalize(phrases[0])).file));audio.onended();assert(plays[1].endsWith(lookup.get(normalize(phrases[1])).file));assert(elements.get('audio-passage').textContent===phrases[1]);assert(elements.get('audio-voice').parentElement.hidden);assert(elements.get('audio-original').hidden);assert.equal(robotCalls,0);runtime.test.stop();const count=plays.length;audio.onended();assert.equal(plays.length,count,'Stopped queue restarted');console.log(`${checked} spoken phrases covered; ${manifest.length} MP3 files present; queue advances and stops without browser speech.`);})().catch(e=>{console.error(e);process.exitCode=1});
